" vimrc file

" Basic configuration
set nocompatible

filetype indent plugin on
packadd termdebug

syntax on

set mouse=a
set encoding=utf-8
set number relativenumber

set autoindent
set backspace=indent,eol,start
set hidden

set incsearch
set ignorecase
set smartcase

set wrapscan

set tabstop=2
set shiftwidth=2
set expandtab
set smarttab
set softtabstop=2

set ruler
set wildmenu
set wildmode=longest,list,full
set splitbelow splitright
set completeopt-=preview

runtime macros/matchit.vim

" Set cursor to vertical line during insert
let &t_ti.="\e[1 q"
let &t_SI.="\e[5 q"
let &t_EI.="\e[1 q"
let &t_te.="\e[0 q"

" Vimtex configs
let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg'

" Key mappings
map <F6> :setlocal spell! spelllang=en_us<CR>
nnoremap gV `[v`]
nnoremap j gj
nnoremap k gk
