" vimrc file

" Plugins

call plug#begin('~/.vim/plugged')

 Plug 'valloric/youcompleteme'
 Plug 'lervag/vimtex'
 Plug 'sirver/ultisnips'

call plug#end()

" Basic configuration
set nocompatible
filetype plugin on
syntax on
set encoding=utf-8
set number relativenumber
set autoindent
set backspace=indent,eol,start
set hidden
set incsearch
set ruler
set wildmenu
set wildmode=longest,list,full
set splitbelow splitright

runtime macros/matchit.vim

set completeopt-=preview

let g:ycm_global_ycm_extra_conf = "~/.vim/.ycm_extra_conf.py"
let g:ycm_add_preview_to_completeopt = 0

let &t_ti.="\e[1 q"
let &t_SI.="\e[5 q"
let &t_EI.="\e[1 q"
let &t_te.="\e[0 q"

let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg'
